### ISSUE TITLE
Tvorba rezervace pro neexistujiciho zakaznika

### ISSUE THREAD

**Issue by FilipMatys** [KratochvilJiri/PISHotel#1]
Pokud vytvarim rezervaci, tak v aktualnim stavu muzu vybrat jedine z existujicich. Pokud ale zvolim moznost vytvorit noveho, tak by se mi mel nabidnout formular pro jeho vytvoreni. Idealne hned pod tlacitkem. Je potom potreba zajistit, aby pred ulozenim pokoje byl ulozen zakaznik (kvuli vazbe).

**Navrh pro implementaci zadani noveho zakaznika:**
Po vyberu moznosti vytvorit noveho se zobrazi pod tlacitkem formular pro tvorbu zakaznika, idealne zobrazen pres direktivu ng-if. Uzivatel pak pokracuje ve vyplnovani rezervace.

**Navrhuji dve moznosti pro ulozeni:**
1) Poslat nejdrive request na server se zakaznikem, po uspesnem ulozeni pripojit zakaznika k rezervaci a az pote odeslat rezervaci k ulozeni.

2) Poslat rezervaci na server vcetne neulozeneho zakaznika. Sluzba pro ulozeni si zkontroluje, zda je zakaznik novy nebo stavajici (ma atribut _id). Pokud novy, tak zavola sluzbu pro ulozeni a nasledne provede ulozeni rezervace se zakaznikem s atributem _id.

**Comment by KratochvilJiri** [comment]
To funguje? Ja když dám "Nový zákazník" v rezervaci, tak mi žádný formluř nevyjede.

**Comment by FilipMatys** [comment]
Prozatim v samostatne vetvi. Zitra domluvime, co dal.
