### ISSUE TITLE
Workflow pro rezervace

### ISSUE THREAD

**Issue by FilipMatys** [KratochvilJiri/PISHotel#12]
Doplnit objekt Reservation o atribut State.

**Hodnoty, kterých bude moci nabývat:**
- Created
- Confirmed
- Canceled
- Completed/Paid

Při vytvoření rezervace je atribut Reservation.State nastaven na hodnotu Created. Po uložení je možné pomocí uživatelského rozhraní ze stavu Created přejít do stavů:
- Confirmed (Pomocí tlačítka "Potvrdit rezervaci")
- Canceled (Pomocí tlačítka "Stornovat rezervaci")

Ze stavu Confirmed je možné přejít do stavu Completed/Paid. 

**Stavy, které jsou konečné:**
- Canceled
- Completed/Paid (Pomocí tlačítka "Potvrdit rezervaci"/"Potvrdit úhradu")

Kontrolu přechodů stavů bude zajišťovat služba ReservationService.checkStateTransition(), která bude implementována na straně serveru a bude volána během uložení. Změna stavu bude probíhat klasickým uložením, tedy v GUI bude nastaven pomocí tlačítka nový stav a následně bude objekt Reservation odeslán na server metodě ReservationService.save().

**Comment by KratochvilJiri** [comment]
Udělám dnes.

**Comment by KratochvilJiri** [comment]
Hotovo.
