### ISSUE TITLE
COP - number

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#16]
Při tvorbě nového zákazníka lze zadat COP jako "string", mělo by být povoleno pouze number (změna typu inputu..).

**Comment by FilipMatys** [comment]
Implementovano pouze na strane serveru, kde se kontroluje, ze retezec obsahuje opravdu jen cislice. Zkusil jsem zmenit typ inputu, ale html ve spojeni s angularem si s tim neumi poradit. 

COP ukladame jako string, protoze jako number by to bylo prilis velke cislo. Pokud do html elementu typu number dojde string, tak ho neumi prevest na cislo. Takze tam zustal input typu text.

**Comment by KratochvilJiri** [comment]
Otestováno.
Poznámka - lze zadat libovolnou délku COP tzn. i napriklad "1", ale to asi resit nebudeme ne?

**Comment by KratochvilJiri** [comment]
Otestováno. Délka cisla resena v #27.
