### ISSUE TITLE
Kalkulace - refresh

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#25]
Po zmene stavu rezervace (tlacitko kalkulace), se vysledna kalkulace zobrazi az po "force refresh" lepsi by bylo aktualizovat automaticky.

**Comment by KratochvilJiri** [comment]
Přidal jsem:

```
$state.go($state.current, {}, {reload: true}).then(function(){
  $scope.showSuccess("Stav rezervace byl úspešně změněn");
})
```

Což vede k refreshi i zobrazeni hlášky o uspesne akci, ale nekde se ztratí obsah hlásky ("Stav rezervace byl úspešně změněn").  

Nepodařilo se mi to tam dostat přes stateParams.. nevím jestli to nějak jde.

**Comment by FilipMatys** [comment]
Refreshovat stránku není dobré řešení. Data by se měla aktualizovat na základě odpovědi ze serveru. Buď opětovným dotazem na detail, nebo (ideálně) využít odpovědi na změnu stavu. Poprosím řešitele o opravu.

**Comment by KratochvilJiri** [comment]
Přepracovane na načtení rezervace, pri prechodu na stav "kalkulace".
Otestovane.
