### ISSUE TITLE
Vytvoreni rezervace v obsazenem terminu

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#26]
Podarilo se mi vytvorit dve rezervace pro jeden pokoj ve stejnem dnu.
Konkretne pro pokoj T206 v datu 1.4-1.4.
Jinak to fungovalo fajn pro delsi data rezervace, bude tam asi nekde chyba v "jednicce".

**Comment by FilipMatys** [comment]
Toto je spíš problém toho, že se nekontroluje délka rezervace. Ta by neměla být rovna nule. Pokud mám totiž termín od X do X, tak mám délku rezervace 0, respektive rezervaci na 0 nocí. 

Zde bych proto poprosil doplnit validaci na délku rezervace, která by měla být větší jak 0.

**Comment by xlenga01** [comment]
Pridal jsem kontrolu na to jestli se data neshodují..., v blizke dobe pushnu...

**Comment by KratochvilJiri** [comment]
Hotovo? Na gitu nic nevidím.

**Comment by FilipMatys** [comment]
Nemotej, prosim, Tome, opravy do jednoho commitu. 

627409c842a532f3951516285285a67f4d02776e
