### ISSUE TITLE
Systém - kontrola inputu na strane serveru.

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#27]
Pro dospele osoby a pocet odebranych sluzeb neni nijak omezene pole - lze zadat libovolne cislo.

**Comment by KratochvilJiri** [comment]
Hodil jsem tam takovou menši odrbávku, tak si to vyzkoušejte a pokud budete souhlasit, můžeme to dát i do dalších inputů (pokud se zada mensi respektive vetsi cislo nez stanovene, tak se to automaticky hodi na min/max). Ty minima, maxima, ktere jde definovat pro input jsou celkem nepouzitelne - nezabrani zadani nekompatibilniho vstupu z klavesnice.

`onKeyUp="if(this.value>99){this.value='99';}else if(this.value<0){this.value='0';}"`

**Comment by FilipMatys** [comment]
Osobně nesouhlasím. "Odrbávka" není dobré řešení. Když už, tak je v těchto případech, kdy je nutná manipulace s inputem, použít angular direktivu. 

Nevalidní vstup je lepší kontrolovat na serveru. Uživatel zadá blbost a server to zjistí. Vrátí hlášku a uživatel ví, že udělal chybu. Takto se mu to změní pod rukama. Dále je jednoduší udělat kontrolu na serveru a pro lepší udržitelnost je lepší to kontrolovat jen na jednom místě.

Za mě tedy kontrola na serveru.

Na kontrolu délky COP bych se vykašlal. Správně by měla kontrola odpovídat normě, ale to je už "placený" improvement.

**Comment by KratochvilJiri** [comment]
Okey, zkusim udelat teda kontrolu na serveru vsech ciselnych udaju a povolit jim nejakou rozumnou delku, co?

**Comment by KratochvilJiri** [comment]
Tento problem je u vetsiny inputu, chce to projit cely system a kontrolovat. Meli bychom se teda domluvit kde. Na strane serveru? A stanovit si nejake delky globalne.

**Comment by FilipMatys** [comment]
Otázka, jestli takové omezení dává vůbec smysl. Nejedná se o chybu, jen z našeho pohledu o blbost. Tato blbost je však na straně uživatele a ze strany systému příliš sémantická.

Pro nás má smysl kontrolovat pouze validní vstup, který je ve zmíněných případech větší nebo roven nule (záleží na konkrétním případě).

Volba maximální hodnoty je zbytečná práce, pokud nemá opodstatnění ve specifikaci.

**Comment by KratochvilJiri** [comment]
Po domluve byla implementovana jen kontrola na zaporna cisla.
Ta uz byla castecne implementovana, tak jsem to jen vsechno prosel a doplnil tam kde to chybelo.
