### ISSUE TITLE
Rezervace - editace uzavrene rezervace

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#28]
V uzavrene (platba potvrzena) rezervaci lze editovat libovolne polozky. To by asi nemelo ne?

**Comment by FilipMatys** [comment]
Týká se jak Platba potvrzena, tak Stornováno.

Ideálním řešením je zabránit na serveru uložení takovéto rezervace. Na frontendu pak nezobrazovat tlačítko uložit.

**Comment by KratochvilJiri** [comment]
Nastavil bych na frontendu inputy formulare na disabled nebo tlacitko ulozit na disabled (asi spis to tlacitko a pod to bych dal informacni hlasku, proc to nejde ulozit), pokud je to v nejakem z techto stavů. 
Tím padem by nebylo nutne to osetrovat na backendu.

**Comment by FilipMatys** [comment]
Nastavení tlačítka na disabled klidně. Informační hlášku bych se už vykašlal. Spíš bych někde zobrazoval aktuální stav rezervace.

Kontrola na serveru ale být musí.
