### ISSUE TITLE
Administrace - pokoje - editace - existujici nazev

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#35]
Po prejmenovani pokoje na existujici nazev a ulozeni se zobrazi pouze hlaska - "Pokoj se nepodarilo ulozi". 
Chtelo by to presne zkontrolovat a specifikovat tu chybu.

**Comment by KratochvilJiri** [comment]
Vyřešeno pomocí dotazu count na ID již existujícich pokojů v DB.
Otestováno.

**Comment by FilipMatys** [comment]
Změna znemožňuje editaci existujícího pokoje při zachování názvu

**Comment by KratochvilJiri** [comment]
Jj, pridam tam jeste kontrolu ID, to by melo pomoci.

**Comment by KratochvilJiri** [comment]
Upraveno, otestovano - editace stavajiciho, editace stavajiciho na jiz existujici nazev, pridani noveho s jiz existujicim nazvem.
