### ISSUE TITLE
express-session modul chybi

### ISSUE THREAD

**Issue by xlenga01** [KratochvilJiri/PISHotel#37]
Upozornoval jsem na to na posledni schuzi - kdyz stahnete projekt z repozitare a date rovnou "node server.js" tak vam to vyhodi, ze modul "express-session" chybi..

Taky se zminovalo, ze by bylo vhodne smazat vsechny lokalni moduly, pac by se meli nainstalovat jako souast kompilace...

**Comment by FilipMatys** [comment]
5f9fa91cfca4c3f56fed28dd1d810796a7167036
