### ISSUE TITLE
Administrace - uživatelé - vytvoření uživatele  typu administrátor

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#42]
Nelze vytvořit uživatele typu administrátor ani editovat stávajícího tohoto typu. Systém vrací chybu: "Role uživatele je povinná".

**Comment by xlenga01** [comment]
Vyreseno

**Comment by KratochvilJiri** [comment]
Takže se to issue může zavřít nebo bude ještě nějaké pokračování?

**Comment by FilipMatys** [comment]
Po otestování zavřít.
