### ISSUE TITLE
Heroku - deploy 

### ISSUE THREAD

**Issue by KratochvilJiri** [KratochvilJiri/PISHotel#44]
Tenhle typ aplikace se dá vcelku bez problému umístit pomocí služby Heroku (https://www.heroku.com/) na WWW. Tzn. Burgetovi bychom mohli poslat i odkaz, kde by si mohl aplikaci proklikat a nemusel by si ji nutně instalovat. 

Pokud chcete, můžeme to tam hodit, jen se musí někdo regnout. Pokud si myslíte, že je to zbytečné, tak nic.

**Comment by FilipMatys** [comment]
https://agile-tor-39348.herokuapp.com

**Comment by KratochvilJiri** [comment]
Paráda 👍  :).
