### ISSUE TITLE
Administrace - služby - vytvoření služby se stejným jménem

### ISSUE THREAD

**Issue by xlenga01** [KratochvilJiri/PISHotel#46]
Lze vytvořit více služeb se stejným jménem.

**Comment by KratochvilJiri** [comment]
Název služby je pouze název, nikoliv nějaký unikátní identifikátor a pokud si někdo udělá dvě služby se stejným názvem..Asi bych to neřešil, ale jak chcete. Pokud ano, měli bychom změnit i model, nejen přidat kontrolu.
